In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime

In [28]:
log_data  = pd.read_csv('access.log', sep='\s+',header=None)
log_data

,0,1,2,3,4,5,6,7,8,9
0,97.105.19.58,-,-,[16/Apr/2019:19:34:42,+0000],GET /api/v1/sales?page=81 HTTP/1.1,200,512495,-,python-requests/2.21.0
1,97.105.19.58,-,-,[16/Apr/2019:19:34:42,+0000],GET /api/v1/items HTTP/1.1,200,3561,-,python-requests/2.21.0
2,97.105.19.58,-,-,[16/Apr/2019:19:34:44,+0000],GET /api/v1/sales?page=82 HTTP/1.1,200,510103,-,python-requests/2.21.0
3,97.105.19.58,-,-,[16/Apr/2019:19:34:46,+0000],GET /api/v1/sales?page=83 HTTP/1.1,200,510003,-,python-requests/2.21.0
4,97.105.19.58,-,-,[16/Apr/2019:19:34:48,+0000],GET /api/v1/sales?page=84 HTTP/1.1,200,511963,-,python-requests/2.21.0
5,97.105.19.58,-,-,[16/Apr/2019:19:34:48,+0000],GET /api/v1/stores HTTP/1.1,200,1328,-,python-requests/2.21.0
6,97.105.19.58,-,-,[16/Apr/2019:19:34:50,+0000],GET /api/v1/sales?page=85 HTTP/1.1,200,510753,-,python-requests/2.21.0
7,97.105.19.58,-,-,[16/Apr/2019:19:34:52,+0000],GET /api/v1/sales?page=86 HTTP/1.1,200,510348,-,python-requests/2.21.0
8,97.105.19.58,-,-,[16/Apr/2019:19:34:52,+0000],GET / HTTP/1.1,200,42,-,python-requests/2.21.0
9,97.105.19.58,-,-,[16/Apr/2019:19:34:53,+0000],GET /api/v1/items HTTP/1.1,200,3561,-,python-requests/2.21.0
10,97.105.19.58,-,-,[16/Apr/2019:19:34:53,+0000],GET /api/v1/items?page=2 HTTP/1.1,200,3659,-,python-requests/2.21.0
11,97.105.19.58,-,-,[16/Apr/2019:19:34:53,+0000],GET /api/v1/items?page=3 HTTP/1.1,200,1787,-,python-requests/2.21.0
12,97.105.19.58,-,-,[16/Apr/2019:19:34:54,+0000],GET /api/v1/sales HTTP/1.1,200,493905,-,python-requests/2.21.0
13,97.105.19.58,-,-,[16/Apr/2019:19:34:54,+0000],GET /api/v1/sales?page=87 HTTP/1.1,200,510540,-,python-requests/2.21.0
14,97.105.19.58,-,-,[16/Apr/2019:19:34:56,+0000],GET /api/v1/sales?page=88 HTTP/1.1,200,512469,-,python-requests/2.21.0
15,97.105.19.58,-,-,[16/Apr/2019:19:34:58,+0000],GET /api/v1/sales?page=89 HTTP/1.1,200,512044,-,python-requests/2.21.0
16,97.105.19.58,-,-,[16/Apr/2019:19:35:01,+0000],GET /api/v1/sales?page=90 HTTP/1.1,200,510438,-,python-requests/2.21.0
17,97.105.19.58,-,-,[16/Apr/2019:19:35:03,+0000],GET /api/v1/sales?page=91 HTTP/1.1,200,511883,-,python-requests/2.21.0
18,97.105.19.58,-,-,[16/Apr/2019:19:35:05,+0000],GET /api/v1/sales?page=92 HTTP/1.1,200,512273,-,python-requests/2.21.0
19,97.105.19.58,-,-,[16/Apr/2019:19:35:07,+0000],GET /api/v1/sales?page=93 HTTP/1.1,200,510147,-,python-requests/2.21.0
20,97.105.19.58,-,-,[16/Apr/2019:19:35:09,+0000],GET /api/v1/sales?page=94 HTTP/1.1,200,510138,-,python-requests/2.21.0
21,97.105.19.58,-,-,[16/Apr/2019:19:35:10,+0000],GET /api/v1/sales?page=95 HTTP/1.1,200,511966,-,python-requests/2.21.0
22,97.105.19.58,-,-,[16/Apr/2019:19:35:12,+0000],GET /api/v1/sales?page=96 HTTP/1.1,200,510046,-,python-requests/2.21.0
23,97.105.19.58,-,-,[16/Apr/2019:19:35:14,+0000],GET /api/v1/sales?page=97 HTTP/1.1,200,509783,-,python-requests/2.21.0
24,97.105.19.58,-,-,[16/Apr/2019:19:35:16,+0000],GET /api/v1/sales?page=98 HTTP/1.1,200,509806,-,python-requests/2.21.0
25,97.105.19.58,-,-,[16/Apr/2019:19:35:18,+0000],GET /api/v1/sales?page=99 HTTP/1.1,200,512312,-,python-requests/2.21.0
26,97.105.19.58,-,-,[16/Apr/2019:19:35:20,+0000],GET /api/v1/sales?page=100 HTTP/1.1,200,512674,-,python-requests/2.21.0
27,97.105.19.58,-,-,[16/Apr/2019:19:35:22,+0000],GET /api/v1/sales?page=101 HTTP/1.1,200,510509,-,python-requests/2.21.0
28,97.105.19.58,-,-,[16/Apr/2019:19:35:24,+0000],GET /api/v1/sales?page=102 HTTP/1.1,200,512612,-,python-requests/2.21.0
29,97.105.19.58,-,-,[16/Apr/2019:19:35:26,+0000],GET /api/v1/sales?page=103 HTTP/1.1,200,512764,-,python-requests/2.21.0
...,...,...,...,...,...,...,...,...,...,...
13944,97.105.19.58,-,-,[17/Apr/2019:12:54:47,+0000],GET /api/v1/sales?page=41 HTTP/1.1,200,511876,-,python-requests/2.21.0
13945,97.105.19.58,-,-,[17/Apr/2019:12:54:48,+0000],GET /api/v1/sales?page=43 HTTP/1.1,200,510448,-,python-requests/2.21.0
13946,97.105.19.58,-,-,[17/Apr/2019:12:54:49,+0000],GET /api/v1/sales?page=42 HTTP/1.1,200,510617,-,python-requests/2.21.0
13947,97.105.19.58,-,-,[17/Apr/2019:12:54:50,+0000],GET /api/v1/sales?page=49 HTTP/1.1,200,510445,-,python-requests/2.21.0
13948,97.105.19.58,-,-,[17/Apr/2019:12:54:50,+0000],GET /api/v1/sales?page=44 HTTP/1.1,200,512701,-,python-requests/2.21.0
13949,97.105.19.58,-,-,[17/Apr/2019:12:54:51,+0000],GET /api/v1/sales?page=45 HTTP/1.1,200,512241,-,python-requests/2.21.0
13950,97.105.19.58,-,-,[17/Apr/2019:12:54:53,+0000],GET /api/v1/sales?page=50 HTTP/1.1,200,510139,-,python-requests/2.21.0
13951,97.105.19.58,-,-,[17/Apr/2019:12:54:54,+0000],GET /api/v1/sales?page=48 HTTP/1.1,200,513027,-,python-requests/2.21.0
13952,97.105.19.58,-,-,[17/Apr/2019:12:54:54,+0000],GET /api/v1/sales?page=46 HTTP/1.1,200,510810,-,python-requests/2.21.0
13953,97.105.19.58,-,-,[17/Apr/2019:12:54:55,+0000],GET /api/v1/sales?page=47 HTTP/1.1,200,511454,-,python-requests/2.21.0
13954,97.105.19.58,-,-,[17/Apr/2019:12:54:57,+0000],GET /api/v1/sales?page=52 HTTP/1.1,200,512589,-,python-requests/2.21.0
13955,97.105.19.58,-,-,[17/Apr/2019:12:54:58,+0000],GET /api/v1/sales?page=54 HTTP/1.1,200,511118,-,python-requests/2.21.0
13956,97.105.19.58,-,-,[17/Apr/2019:12:54:59,+0000],GET /api/v1/sales?page=53 HTTP/1.1,200,511577,-,python-requests/2.21.0
13957,97.105.19.58,-,-,[17/Apr/2019:12:54:59,+0000],GET /api/v1/sales?page=58 HTTP/1.1,200,510020,-,python-requests/2.21.0
13958,97.105.19.58,-,-,[17/Apr/2019:12:55:00,+0000],GET /api/v1/sales?page=51 HTTP/1.1,200,511530,-,python-requests/2.21.0
13959,97.105.19.58,-,-,[17/Apr/2019:12:55:01,+0000],GET /api/v1/sales?page=55 HTTP/1.1,200,513736,-,python-requests/2.21.0
13960,97.105.19.58,-,-,[17/Apr/2019:12:55:03,+0000],GET /api/v1/sales?page=56 HTTP/1.1,200,510120,-,python-requests/2.21.0
13961,97.105.19.58,-,-,[17/Apr/2019:12:55:03,+0000],GET /api/v1/sales?page=59 HTTP/1.1,200,511959,-,python-requests/2.21.0
13962,97.105.19.58,-,-,[17/Apr/2019:12:55:04,+0000],GET /api/v1/sales?page=63 HTTP/1.1,200,512205,-,python-requests/2.21.0
13963,97.105.19.58,-,-,[17/Apr/2019:12:55:06,+0000],GET /api/v1/sales?page=57 HTTP/1.1,200,509933,-,python-requests/2.21.0
13964,97.105.19.58,-,-,[17/Apr/2019:12:55:06,+0000],GET /api/v1/sales?page=61 HTTP/1.1,200,510084,-,python-requests/2.21.0
13965,97.105.19.58,-,-,[17/Apr/2019:12:55:08,+0000],GET /api/v1/sales?page=60 HTTP/1.1,200,510123,-,python-requests/2.21.0
13966,97.105.19.58,-,-,[17/Apr/2019:12:55:09,+0000],GET /api/v1/sales?page=67 HTTP/1.1,200,510139,-,python-requests/2.21.0
13967,97.105.19.58,-,-,[17/Apr/2019:12:55:09,+0000],GET /api/v1/sales?page=66 HTTP/1.1,200,513313,-,python-requests/2.21.0
13968,97.105.19.58,-,-,[17/Apr/2019:12:55:09,+0000],GET /api/v1/sales?page=64 HTTP/1.1,200,511251,-,python-requests/2.21.0
13969,97.105.19.58,-,-,[17/Apr/2019:12:55:12,+0000],GET /api/v1/sales?page=62 HTTP/1.1,200,511544,-,python-requests/2.21.0
13970,97.105.19.58,-,-,[17/Apr/2019:12:55:12,+0000],GET /api/v1/sales?page=65 HTTP/1.1,200,511201,-,python-requests/2.21.0
13971,97.105.19.58,-,-,[17/Apr/2019:12:55:13,+0000],GET /api/v1/sales?page=73 HTTP/1.1,200,511781,-,python-requests/2.21.0
13972,97.105.19.58,-,-,[17/Apr/2019:12:55:13,+0000],GET /api/v1/sales?page=69 HTTP/1.1,200,510136,-,python-requests/2.21.0
13973,97.105.19.58,-,-,[17/Apr/2019:12:55:14,+0000],GET /api/v1/sales?page=71 HTTP/1.1,200,510166,-,python-requests/2.21.0

In [29]:
log_data[3].dtype

dtype('O')

In [30]:
for col in log_data.columns:
    print(col, log_data[col].dtype)

0 object
1 object
2 object
3 object
4 object
5 object
6 int64
7 int64
8 object
9 object

### Concat columns 5-9 into a single column. This column represents the requests made

In [31]:
log_data['Request']= log_data[5]+log_data[6].astype(str)+log_data[7].astype(str)+log_data[8]+log_data[9]
log_data.head()

,0,1,2,3,4,5,6,7,8,9,Request
0,97.105.19.58,-,-,[16/Apr/2019:19:34:42,+0000],GET /api/v1/sales?page=81 HTTP/1.1,200,512495,-,python-requests/2.21.0,GET /api/v1/sales?page=81 HTTP/1.1200512495-py...
1,97.105.19.58,-,-,[16/Apr/2019:19:34:42,+0000],GET /api/v1/items HTTP/1.1,200,3561,-,python-requests/2.21.0,GET /api/v1/items HTTP/1.12003561-python-reque...
2,97.105.19.58,-,-,[16/Apr/2019:19:34:44,+0000],GET /api/v1/sales?page=82 HTTP/1.1,200,510103,-,python-requests/2.21.0,GET /api/v1/sales?page=82 HTTP/1.1200510103-py...
3,97.105.19.58,-,-,[16/Apr/2019:19:34:46,+0000],GET /api/v1/sales?page=83 HTTP/1.1,200,510003,-,python-requests/2.21.0,GET /api/v1/sales?page=83 HTTP/1.1200510003-py...
4,97.105.19.58,-,-,[16/Apr/2019:19:34:48,+0000],GET /api/v1/sales?page=84 HTTP/1.1,200,511963,-,python-requests/2.21.0,GET /api/v1/sales?page=84 HTTP/1.1200511963-py...

In [32]:
log_data = log_data.drop([1, 2, 4, 5, 6, 7, 8, 9], axis=1)

In [37]:
log_data = log_data.rename(columns={0:'IP_address',3: 'date_time'})

In [38]:
log_data.head()

,IP_address,date_time,Request
0,97.105.19.58,[16/Apr/2019:19:34:42,GET /api/v1/sales?page=81 HTTP/1.1200512495-py...
1,97.105.19.58,[16/Apr/2019:19:34:42,GET /api/v1/items HTTP/1.12003561-python-reque...
2,97.105.19.58,[16/Apr/2019:19:34:44,GET /api/v1/sales?page=82 HTTP/1.1200510103-py...
3,97.105.19.58,[16/Apr/2019:19:34:46,GET /api/v1/sales?page=83 HTTP/1.1200510003-py...
4,97.105.19.58,[16/Apr/2019:19:34:48,GET /api/v1/sales?page=84 HTTP/1.1200511963-py...

In [43]:
log_data['date_time'] = log_data['date_time'].str.replace('[','')

In [44]:
log_data.head()

,IP_address,date_time,Request
0,97.105.19.58,16/Apr/2019:19:34:42,GET /api/v1/sales?page=81 HTTP/1.1200512495-py...
1,97.105.19.58,16/Apr/2019:19:34:42,GET /api/v1/items HTTP/1.12003561-python-reque...
2,97.105.19.58,16/Apr/2019:19:34:44,GET /api/v1/sales?page=82 HTTP/1.1200510103-py...
3,97.105.19.58,16/Apr/2019:19:34:46,GET /api/v1/sales?page=83 HTTP/1.1200510003-py...
4,97.105.19.58,16/Apr/2019:19:34:48,GET /api/v1/sales?page=84 HTTP/1.1200511963-py...

In [50]:
log_data['date_time'] = log_data['date_time'].str.replace(':',' ',n=1)

In [51]:
log_data.head()

,IP_address,date_time,Request
0,97.105.19.58,16/Apr/2019 19:34:42,GET /api/v1/sales?page=81 HTTP/1.1200512495-py...
1,97.105.19.58,16/Apr/2019 19:34:42,GET /api/v1/items HTTP/1.12003561-python-reque...
2,97.105.19.58,16/Apr/2019 19:34:44,GET /api/v1/sales?page=82 HTTP/1.1200510103-py...
3,97.105.19.58,16/Apr/2019 19:34:46,GET /api/v1/sales?page=83 HTTP/1.1200510003-py...
4,97.105.19.58,16/Apr/2019 19:34:48,GET /api/v1/sales?page=84 HTTP/1.1200511963-py...

In [52]:
log_data['date_parsed'] = pd.to_datetime(log_data['date_time'], format = "%d/%b/%y %H%M%S", infer_datetime_format=True)

In [53]:
log_data.head()

,IP_address,date_time,Request,date_parsed
0,97.105.19.58,16/Apr/2019 19:34:42,GET /api/v1/sales?page=81 HTTP/1.1200512495-py...,2019-04-16 19:34:42
1,97.105.19.58,16/Apr/2019 19:34:42,GET /api/v1/items HTTP/1.12003561-python-reque...,2019-04-16 19:34:42
2,97.105.19.58,16/Apr/2019 19:34:44,GET /api/v1/sales?page=82 HTTP/1.1200510103-py...,2019-04-16 19:34:44
3,97.105.19.58,16/Apr/2019 19:34:46,GET /api/v1/sales?page=83 HTTP/1.1200510003-py...,2019-04-16 19:34:46
4,97.105.19.58,16/Apr/2019 19:34:48,GET /api/v1/sales?page=84 HTTP/1.1200511963-py...,2019-04-16 19:34:48

In [55]:
log_data['date_parsed'].dtype

dtype('<M8[ns]')

In [57]:
log_data.to_csv('logs.csv')